
# -*- makefile -*-
# Do not edit this file.
# This file will be overwritten by the project setup script.

RAW_SIMICS_BASE=/home/marek/simics/simics-6.0.146
RAW_SIMICS_MODEL_BUILDER=/home/marek/simics/simics-6.0.146
RAW_EML_PACKAGE=
RAW_DODOC_PKG=/home/marek/simics/simics-6.0.146

RAW_SIMICS_PACKAGE_LIST=

INCLUDE_PATHS = /home/marek/simics/simics-6.0.146/src/include
CXX_INCLUDE_PATHS = /home/marek/simics/simics-6.0.146/linux64/api
DML_INCLUDE_PATHS = /home/marek/simics/simics-6.0.146/linux64/bin/dml/api
HOST_TYPE = linux64
