
# -*- makefile -*-
# Do not edit this file.
# This file will be overwritten by the project setup script.

RAW_SIMICS_BASE=/home/xxbykowm/simics/simics-6.0.157
RAW_SIMICS_MODEL_BUILDER=/home/xxbykowm/simics/simics-6.0.157
RAW_EML_PACKAGE=
RAW_DODOC_PKG=/home/xxbykowm/simics/simics-6.0.157

RAW_SIMICS_PACKAGE_LIST=/home/xxbykowm/simics/my-simics-project-1/.package-list

INCLUDE_PATHS = /home/xxbykowm/simics/simics-6.0.157/src/include
CXX_INCLUDE_PATHS = /home/xxbykowm/simics/simics-6.0.157/linux64/api
DML_INCLUDE_PATHS = /home/xxbykowm/simics/simics-6.0.157/linux64/bin/dml/api
HOST_TYPE = linux64
